# Generated by Django 4.2.1 on 2024-06-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laptops", "0002_vendor_mylaptop_laptop_vendor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyLaptop",
        ),
        migrations.CreateModel(
            name="Overview",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("laptops.laptop",),
        ),
    ]
