# Generated by Django 4.2.1 on 2024-08-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laptops", "0003_delete_mylaptop_overview"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="image",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
