# Generated by Django 4.2.1 on 2024-08-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("laptops", "0005_question_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="laptops.question",
            ),
        ),
    ]
