# Generated by Django 4.2.1 on 2024-08-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("laptops", "0006_question_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="attachment_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="laptops.question",
            ),
        ),
    ]
