# Generated by Django 5.1 on 2024-08-26 11:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laptops", "0007_question_attachment_required_alter_question_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="comment",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
